<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <title>
   Zarkan Jewelry
  </title>
  <script src="https://cdn.tailwindcss.com">
  </script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet"/>
 </head>
 <body class="bg-white text-gray-800">
  <!-- Top Banner -->
  <div class="bg-red-700 text-white text-center py-2 text-sm">
   Get 5% OFF on All Prepaid Orders, Use Code: PAY5
  </div>
  <!-- Header -->
  <header class="flex items-center justify-between px-4 py-2 border-b">
   <div class="flex items-center space-x-4">
    <i class="fas fa-bars text-xl"></i>
    <img alt="Zarkan Logo" class="h-10" height="40" src="https://storage.googleapis.com/a1aa/image/vrJoeVyGLs0aMqoDnDYZUBhUqX3OgxOxDJua7AmNnyKeg0BUA.jpg" width="100"/>
   </div>
   <div class="flex items-center space-x-4">
    <i class="fas fa-search text-xl"></i>
    <i class="fas fa-heart text-xl"></i>
    <i class="fas fa-shopping-bag text-xl"></i>
    <i class="fas fa-user text-xl"></i>
   </div>
  </header>
  <!-- Main Content -->
  <main class="px-4 py-6">
   <h1 class="text-2xl font-semibold text-center mb-4">
    Perfect Gift for Your Partner
   </h1>
   <div class="flex items-center justify-between mb-4">
    <div class="flex items-center space-x-2">
     <span class="text-gray-600">Sort:</span>
     <select class="border border-gray-300 rounded px-2 py-1">
      <option>Best selling</option>
     </select>
    </div>
    <div class="flex items-center space-x-2">
     <i class="fas fa-th-large text-xl"></i>
     <i class="fas fa-th-list text-xl"></i>
    </div>
   </div>
   <!-- Product Grid -->
   <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
    <!-- Loop to create 20 products -->
    <script>
      const products = [
        { name: "Suit Salwar 1", oldPrice: "1999.00", price: "899.00", discount: "56", img: "https://storage.googleapis.com/a1aa/image/aBxnqvWU1xLqANZ7IUxM8oGMEHop2LQhhqJi3XcLaAxpIdAF.jpg" },
        { name: "Suit Salwar 2", oldPrice: "2999.00", price: "999.00", discount: "67", img: "https://storage.googleapis.com/a1aa/image/SZrrzCeWeFqpFUCnVix5JIlUSgfm6pCeiRa33Ir7MX2fVkOgC.jpg" },
        { name: "Suit Salwar 3", oldPrice: "1499.00", price: "699.00", discount: "58", img: "https://storage.googleapis.com/a1aa/image/XJsB2MURekXoFqAvqemDmbef6y71JisbOZNEgtuMODmuKSHQB.jpg" },
        { name: "Suit Salwar 4", oldPrice: "2599.00", price: "999.00", discount: "61", img: "https://storage.googleapis.com/a1aa/image/IgkiQzfZDH0cCqZfegiFmZAiWrf89QRc3Ku0bAyjiHEPLSHQB.jpg" },
        { name: "Suit Salwar 5", oldPrice: "1999.00", price: "999.00", discount: "50", img: "https://storage.googleapis.com/a1aa/image/eGNgGURy1RQLE6U3VerVgH5m5JXfdcYLH1qhuYaltdZiFpDoA.jpg" }
      ];

      for (let i = 1; i <= 20; i++) {
        let p = products[i % 5]; 
        document.write(`
          <div class="border p-4 rounded-lg">
            <div class="relative">
              <img alt="${p.name}" class="w-full h-48 object-cover" src="${p.img}" />
              <span class="absolute top-2 left-2 bg-red-500 text-white text-xs px-2 py-1 rounded">-${p.discount}%</span>
            </div>
            <h2 class="text-lg font-semibold mt-4">${p.name}</h2>
            <div class="flex items-center mt-2">
              <div class="flex items-center text-yellow-500">
                <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>
              </div>
              <span class="text-gray-600 ml-2">${Math.floor(Math.random() * 50 + 1)} reviews</span>
            </div>
            <div class="text-gray-500 line-through mt-2">Rs. ${p.oldPrice}</div>
            <div class="text-xl font-bold text-gray-800">Rs. ${p.price}</div>
            <form action="upi://pay" method="get">
              <input name="pa" type="hidden" value="hanjla1@paytm"/>
              <input name="pn" type="hidden" value="Zarkan"/>
              <input name="tn" type="hidden" value="Payment for ${p.name}"/>
              <input name="am" type="hidden" value="${p.price}"/>
              <input name="cu" type="hidden" value="INR"/>
              <button class="w-full bg-white border border-gray-300 text-gray-800 py-2 mt-4 rounded-lg flex items-center justify-center space-x-2" type="submit">
                <i class="fas fa-shopping-bag"></i> <span>BUY NOW</span>
              </button>
            </form>
          </div>
        `);
      }
    </script>
   </div>
  </main>
 </body>
</html>
